//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class discussinfos
    {
        public long FDiscussId { get; set; }
        public System.DateTime FDiscussTime { get; set; }
        public long FAuthorId { get; set; }
        public long FParentDiscussId { get; set; }
        public long FDocId { get; set; }
        public string FDocText { get; set; }
    }
}
