//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class docclss
    {
        public int FDocCLSID { get; set; }
        public System.DateTime FCREATETIME { get; set; }
        public string FCLSNAME { get; set; }
        public string FCLSDESCRIBE { get; set; }
    }
}
