//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class docclsrelations
    {
        public int FLOWID { get; set; }
        public int FDOCCLSID { get; set; }
        public int FPARENTDOCCLSID { get; set; }
        public int FLEVEL { get; set; }
        public string FSTATUS { get; set; }
    }
}
