//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class docclassts
    {
        public long FDocId { get; set; }
        public int FDocCLSID { get; set; }
        public Nullable<System.DateTime> FRecordTime { get; set; }
    }
}
