//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dockeywords
    {
        public long FDocId { get; set; }
        public string FKeyWord { get; set; }
        public short FKeySeq { get; set; }
        public Nullable<sbyte> FKeyScore { get; set; }
    }
}
