//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class docstores
    {
        public long FDocId { get; set; }
        public int FDocSegNo { get; set; }
        public short FDocSegLength { get; set; }
        public System.DateTime FDocRecordTime { get; set; }
        public string FDocSegText { get; set; }
    }
}
