//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class docs
    {
        public long FDocId { get; set; }
        public System.DateTime FDocCreateTime { get; set; }
        public System.DateTime FDocModifyTime { get; set; }
        public long FAuthorId { get; set; }
        public sbyte FDeleteFlag { get; set; }
        public int FDocTextLength { get; set; }
        public sbyte FPublishFlag { get; set; }
        public sbyte FIsSignature { get; set; }
        public sbyte FCanDiscuss { get; set; }
        public string FDocBriefDescribe { get; set; }
        public string FDocTitle { get; set; }
        public string FSubTitle { get; set; }
    }
}
