//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class docstatinfos
    {
        public long FDocId { get; set; }
        public System.DateTime FLastAccessTime { get; set; }
        public int FDiscussCount { get; set; }
        public System.DateTime FLastDiscussTime { get; set; }
        public int FReadCount { get; set; }
        public System.DateTime FLastReadTime { get; set; }
    }
}
