//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class filemaps
    {
        public long FLOWID { get; set; }
        public string FRELATEURL { get; set; }
        public string FFILENAME { get; set; }
        public string FFILEEXTEND { get; set; }
        public int FFILETYPE { get; set; }
        public System.DateTime FCREATETIME { get; set; }
        public long FFOLDERPATH { get; set; }
    }
}
