//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class menus
    {
        public int FMENUID { get; set; }
        public int FParentMenuId { get; set; }
        public string FMENUNAME { get; set; }
        public string FMENUTIPS { get; set; }
        public string FMENUURL { get; set; }
        public string FMENUSTATUS { get; set; }
        public System.DateTime FCREATETIME { get; set; }
    }
}
