//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleauthrights
    {
        public int FLOWID { get; set; }
        public int FROLEID { get; set; }
        public int FMENUID { get; set; }
    }
}
