//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userselfsettings
    {
        public long FUserId { get; set; }
        public string FSettingNo { get; set; }
        public string FSettingDesc { get; set; }
        public string FSettingValue { get; set; }
    }
}
