//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public long FUSERID { get; set; }
        public string FUSERNO { get; set; }
        public string FUSERNAME { get; set; }
        public string FUSERNICKNAME { get; set; }
        public System.DateTime FUSERREGTIME { get; set; }
        public string FUSERLEVEL { get; set; }
        public Nullable<System.DateTime> FUSERBIRTHDAY { get; set; }
        public string FUSERMOBILENO { get; set; }
        public string FUSERQQNO { get; set; }
        public string FUSERWXID { get; set; }
        public string FUSERMAIL { get; set; }
        public string FUSERSTATUS { get; set; }
        public string FUSERTELNO { get; set; }
        public string FPASSWORD { get; set; }
    }
}
